// Crafted with ❤ at Breu, Inc. <info@breu.io>, Copyright © 2024, 2025.
//
// Functional Source License, Version 1.1, Apache 2.0 Future License
//
// We hereby irrevocably grant you an additional license to use the Software under the Apache License, Version 2.0 that
// is effective on the second anniversary of the date we make the Software available. On or after that date, you may use
// the Software under the Apache License, Version 2.0, in which case the following will apply:
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License.
//
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

package config

import (
	"context"
	"crypto/hmac"
	"crypto/sha256"
	"encoding/hex"
	"net/http"

	"github.com/bradleyfalzon/ghinstallation/v2"
	"github.com/go-playground/validator/v10"
	gh "github.com/google/go-github/v62/github"

	pkgerrors "go.breu.io/quantm/internal/hooks/github/errors"
)

type (
	// Config holds configuration settings for the GitHub integration.
	Config struct {
		AppID              int64  `koanf:"APP_ID" validate:"required"`         // GitHub App ID.
		ClientID           string `koanf:"CLIENT_ID" validate:"required"`      // GitHub Client ID.
		WebhookSecret      string `koanf:"WEBHOOK_SECRET" validate:"required"` // Secret for verifying webhook requests.
		PrivateKey         string `koanf:"PRIVATE_KEY" validate:"required"`    // Private key for the GitHub API.
		PrivateKeyIsBase64 bool   `koanf:"PRIVATE_KEY_IS_BASE64"`              // If true, the private key is base64 encoded.
	}

	// ConfigOption is a function that modifies a Config.
	ConfigOption func(*Config)
)

func (cfg *Config) Validate() error {
	validate := validator.New()
	return validate.Struct(cfg)
}

// Start is a no-op function that satisfies the graceful Service interface.
func (cfg *Config) Start(ctx context.Context) error { return nil }

// Stop is a no-op function that satisfies the graceful Service interface.
func (cfg *Config) Stop(ctx context.Context) error { return nil }

// SignPayload generates a signature for a given payload.
//
// Calculates the HMAC-SHA256 hash of the payload using the webhook secret. Returns the base64 encoded signature in the
// format "sha256=<hash>".
func (cfg *Config) SignPayload(payload []byte) string {
	key := hmac.New(sha256.New, []byte(cfg.WebhookSecret))
	key.Write(payload)
	result := "sha256=" + hex.EncodeToString(key.Sum(nil))

	return result
}

// VerifyWebhookSignature verifies the signature of a webhook payload.
//
// Verifies that the provided signature matches the signature generated by signing the payload with the webhook secret.
// Returns an error if the signatures don't match.
func (cfg *Config) VerifyWebhookSignature(payload []byte, signature string) error {
	result := cfg.SignPayload(payload)

	if result != signature {
		return pkgerrors.ErrVerifySignature
	}

	return nil
}

// GetClientForInstallationID retrieves a GitHub client for a specific installation ID.
//
// Creates a new client for the specified installation ID using the GitHub Installation API and uses the private key
// from the configuration to authenticate.
func (cfg *Config) GetClientForInstallationID(installationID int64) (*gh.Client, error) {
	transport, err := ghinstallation.New(http.DefaultTransport, cfg.AppID, installationID, []byte(cfg.PrivateKey))
	if err != nil {
		return nil, err
	}

	client := gh.NewClient(&http.Client{Transport: transport})

	return client, nil
}
